### ISSUE TITLE
[ISSUE] No Defrost Functions and seats not heating

### ISSUE THREAD

**Issue by jgrob1** [ad-ha/mg-saic-ha#99]
### Home Assistant Version

2025.1.4

### MG/SAIC Integration Version

0.9.1

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Since updating to 0.9.1 I have lost the front and rear Defrost functions. They don't appear as entities to control at all.

![Image](https://github.com/user-attachments/assets/06dc9e34-b82e-4eed-83cb-fbe9774874e8)

Incidentally, the heated seats function now appears, and successfully switches on the engine when asked for, but doesn't actually switch on the heated seats.

Logs below. I hope these are the right ones.

### Logs

```yaml
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:366
integration: Switch (documentation, issues)
First occurred: 19:08:23 (1 occurrences)
Last logged: 19:08:23

Error while setting up mg_saic platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/switch.py", line 52, in async_setup_entry
    SAICMGHeatedSeatsSwitch(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        coordinator,
        ^^^^^^^^^^^^
    ...<5 lines>...
        "front_left",
        ^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/mg_saic/switch.py", line 386, in __init__
    super().__init__(coordinator)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: SAICMGVehicleSwitch.__init__() missing 6 required positional arguments: 'client', 'entry', 'vin_info', 'vin', 'name', and 'icon'

Next Log;

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 16:35:27 (1 occurrences)
Last logged: 16:35:27

Error setting up entry MG SAIC - LSJW94U99RG051600 for mg_saic
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/__init__.py", line 47, in async_setup_entry
    await coordinator.async_setup()
  File "/config/custom_components/mg_saic/coordinator.py", line 367, in async_setup
    await self.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 306, in async_config_entry_first_refresh
    await self._async_refresh(
        log_failures=False, raise_on_auth_failed=True, raise_on_entry_error=True
    )
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/coordinator.py", line 444, in _async_update_data
    data["status"] = await self._fetch_with_retries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/mg_saic/coordinator.py", line 737, in _fetch_with_retries
    data = await fetch_func()
           ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/api.py", line 125, in get_vehicle_status
    vehicle_status = await self._make_api_call(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.saic_api.get_vehicle_status, self.vin
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/mg_saic/api.py", line 46, in _make_api_call
    return await api_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/saic_ismart_client_ng/api/vehicle/__init__.py", line 15, in get_vehicle_status
    return await self.execute_api_call_with_event_id(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/saic_ismart_client_ng/api/base.py", line 139, in execute_api_call_with_event_id
    return await execute_api_call_with_event_id_inner(event_id='0')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 121, in __call__
    await self.sleep(do)  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 718, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError





next log:
```

**Comment by ad-ha** [comment]
Duplicated with #98
